taskito/config/routes.rb
Taskito::Application.routes.draw do
  resources :tasqs

  devise_for :users

  resources :projects

  resources :users

  root :to => "projects#index"

end

taskito/app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :name, :repo
  
   belongs_to :user
   has_many :tasqs
end

taskito/app/models/tasq.rb
class Tasq < ActiveRecord::Base
  attr_accessible :name, :status_id, :user_id, :project_id
  
  has_many :user_tasqs
  has_many :users, :through => :user_tasqs
  belongs_to :users
end

taskito/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :name, :username, :email
  
  has_many :user_projects
  has_many :projects, :through => :user_projects
  
  has_many :user_tasqs
  has_many :tasqs, :through => :user_tasqs
  
end

taskito/app/models/user_project.rb
class UserProject < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

taskito/app/models/user_projects.rb
class UserProjects < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
end

taskito/app/models/user_tasq.rb
class UserTasq < ActiveRecord::Base
  belongs_to :user
  belongs_to :tasq
end

taskito/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

taskito/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @projects = current_user.projects.all()
  end
  
  def show
    @project = Project.find(params[:id])
    @tasq = @project.tasqs.new
    @tasqs = @project.tasqs.all()
  end
  
  def new
    @project = Project.new
  end
  
  def create
    
    @project = Project.new(params[:project])
    
    if @project.save
      @userproject = UserProject.new()
      @userproject.project_id = @project.id
      @userproject.user_id = current_user.id
      @userproject.save()
      
      flash[:notice] = "Successfully created project."
      redirect_to @project
    else
      render :action => 'new'
    end
  end
  
  def edit
    @project = Project.find(params[:id])
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(params[:project])
      flash[:notice] = "Successfully updated project."
      redirect_to @project
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:notice] = "Successfully destroyed project."
    redirect_to projects_url
  end
end

taskito/app/controllers/tasqs_controller.rb
class TasqsController < ApplicationController
  def index
    @tasqs = Tasq.all
  end
  
  def show
    @tasq = Tasq.find(params[:id])
  end
  
  def new
    @tasq = Tasq.new
  end
  
  def create
    @tasq = Tasq.new(params[:tasq])
    @tasq.user_id=current_user.id 
    @tasq.status_id=1
    if @tasq.save                                       
      
      #-- replace these user_ids by the one sent by the autocomplete ajax:
      worker = UserTasq.new(:tasq_id=>@tasq.id,:user_id=>"2",:role=>"w")    # --- Worker Role
      reviewer = UserTasq.new(:tasq_id=>@tasq.id,:user_id=>current_user.id,:role=>"r")  # --- Reviewer Role
      worker.save
      reviewer.save
      
      flash[:notice] = "Successfully created tasq."
      redirect_to @tasq
    else
      render :action => 'new'
    end
  end
  
  def edit
    @tasq = Tasq.find(params[:id])
  end
  
  def update
    @tasq = Tasq.find(params[:id])
    if @tasq.update_attributes(params[:tasq])
      flash[:notice] = "Successfully updated tasq."
      redirect_to @tasq
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @tasq = Tasq.find(params[:id])
    @tasq.destroy
    flash[:notice] = "Successfully destroyed tasq."
    redirect_to tasqs_url
  end
end

taskito/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
     respond_to do |format|
        format.json { render :json => @users, :callback => params[:callback] }
        format.html
    end
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "Successfully created user."
      redirect_to @user
    else
      render :action => 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:notice] = "Successfully updated user."
      redirect_to @user
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = "Successfully destroyed user."
    redirect_to users_url
  end
end

taskito/app/helpers/application_helper.rb
module ApplicationHelper
end

taskito/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= "Invalid Fields"
    options[:message] ||= "Correct the following errors and try again."
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

taskito/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

taskito/app/helpers/projects_helper.rb
module ProjectsHelper
end

taskito/app/helpers/tasqs_helper.rb
module TasqsHelper
end

taskito/app/helpers/users_helper.rb
module UsersHelper
end

taskito/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

taskito/app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <!-- <p>
      <%= f.label :repo %><br />
      <%= f.text_field :repo %>
    </p> -->
  <p><%= f.submit %></p>
<% end %>

taskito/app/views/projects/edit.html.erb
<% title "Edit Project" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @project %> |
  <%= link_to "View All", projects_path %>
</p>

taskito/app/views/projects/index.html.erb
<% title "Projects" %>

<table>
  <tr>
    <th>Name</th>
    <th>Repo</th>
  </tr>
  <% for project in @projects %>
    <tr>
      <td><%= project.name %></td>
      <td><%= project.repo %></td>
      <td><%= link_to "Add Task", project %></td>
      <td><%= link_to "Edit", edit_project_path(project) %></td>
      <td><%= link_to "Destroy", project, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Project", new_project_path %></p>

taskito/app/views/projects/new.html.erb
<% title "New Project" %>
<%= render 'form' %>

<p><%= link_to "Back to List", projects_path %></p>

taskito/app/views/projects/show.html.erb
<h1>
   <%= @project.name %>
</h1>


<%= form_for @tasq do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label "Task Descripction" %><br />
    <%= f.text_area :name, :cols=>70, :rows=>3 %>
	<%= f.hidden_field :project_id%>
  </p>
  <p><button class="blue-pill">Add Task</button></p>
<% end %>

<h3>
Current Tasks
</h3>
 
<% for tasq in @tasqs %>
    <%= tasq.name %> <br/>
 <% end %>

<p>
  <%= link_to "Edit", edit_project_path(@project) %> |
  <%= link_to "Destroy", @project, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", projects_path %>
</p>

taskito/app/views/tasqs/_form.html.erb
<%= form_for @tasq do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name, :size=>100 %>
  </p>
  <p>
    <%= f.label :worker %><br />
    <%= text_field_tag :worker %>
  </p>
  <p>
    <%= f.label :reviewers %><br />
    <%= text_field_tag :reviewers %>
  </p>
  <p><%= f.submit %></p>
<% end %>

taskito/app/views/tasqs/edit.html.erb
<% title "Edit Tasq" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @tasq %> |
  <%= link_to "View All", tasqs_path %>
</p>

taskito/app/views/tasqs/index.html.erb
<% title "Tasqs" %>

<table>
  <tr>
    <th>Name</th>
    <th>Status</th>
    <th>User</th>
  </tr>
  <% for tasq in @tasqs %>
    <tr>
      <td><%= tasq.name %></td>
      <td><%= tasq.status_id %></td>
      <td><%= tasq.user_id %> <%=tasq.project_id%></td>

      <td><%= link_to "Show", tasq %></td>
      <td><%= link_to "Edit", edit_tasq_path(tasq) %></td>
      <td><%= link_to "Destroy", tasq, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Tasq", new_tasq_path %></p>

taskito/app/views/tasqs/new.html.erb
<% title "New Tasq" %>

<%= render 'form' %>

<p><%= link_to "Back to List", tasqs_path %></p>

taskito/app/views/tasqs/show.html.erb
<% title "Tasq" %>

<p>
  <strong>Name:</strong>
  <%= @tasq.name %>
</p>
<p>
  <strong>Status:</strong>
  <%= @tasq.status_id %>
</p>
<p>
  <strong>User:</strong>
  <%= @tasq.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_tasq_path(@tasq) %> |
  <%= link_to "Destroy", @tasq, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", tasqs_path %>
</p>

taskito/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p><%= f.submit %></p>
<% end %>

taskito/app/views/users/edit.html.erb
<% title "Edit User" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @user %> |
  <%= link_to "View All", users_path %>
</p>

taskito/app/views/users/index.html.erb
<% title "Users" %>

<table>
  <tr>
    <th>Name</th>
    <th>Username</th>
    <th>Email</th>
  </tr>
  <% for user in @users %>
    <tr>
		
       <td><%= user.email %></td>
      <td><%= link_to "Show", user %></td>
      <td><%= link_to "Edit", edit_user_path(user) %></td>
      <td><%= link_to "Destroy", user, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New User", new_user_path %></p>

taskito/app/views/users/new.html.erb
<% title "New User" %>

<%= render 'form' %>

<p><%= link_to "Back to List", users_path %></p>

taskito/app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

taskito/app/views/users/show.html.erb
<% title "User" %>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <%= link_to "Edit", edit_user_path(@user) %> |
  <%= link_to "Destroy", @user, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", users_path %>
</p>